//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cykelstaden.XF.Resources.Icons
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IconFont
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IconFont()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cykelstaden.XF.Resources.Icons.IconFont", typeof(IconFont).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to alt_route.
        /// </summary>
        public static string AltRoute
        {
            get
            {
                return ResourceManager.GetString("AltRoute", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to apps.
        /// </summary>
        public static string Apps
        {
            get
            {
                return ResourceManager.GetString("Apps", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to arrow_forward_ios.
        /// </summary>
        public static string ArrowForwardIos
        {
            get
            {
                return ResourceManager.GetString("ArrowForwardIos", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to dark_mode.
        /// </summary>
        public static string DarkMode
        {
            get
            {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to directions_bike.
        /// </summary>
        public static string DirectionsBike
        {
            get
            {
                return ResourceManager.GetString("DirectionsBike", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to info.
        /// </summary>
        public static string Info
        {
            get
            {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to local_gas_station.
        /// </summary>
        public static string LocalGasStation
        {
            get
            {
                return ResourceManager.GetString("LocalGasStation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to local_parking.
        /// </summary>
        public static string LocalParking
        {
            get
            {
                return ResourceManager.GetString("LocalParking", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to location_on.
        /// </summary>
        public static string LocationOn
        {
            get
            {
                return ResourceManager.GetString("LocationOn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to menu.
        /// </summary>
        public static string Menu
        {
            get
            {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to notifications.
        /// </summary>
        public static string Notifications
        {
            get
            {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to policy.
        /// </summary>
        public static string Policy
        {
            get
            {
                return ResourceManager.GetString("Policy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to quiz.
        /// </summary>
        public static string Quiz
        {
            get
            {
                return ResourceManager.GetString("Quiz", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to report.
        /// </summary>
        public static string Report
        {
            get
            {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string Save
        {
            get
            {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings
        {
            get
            {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to traffic.
        /// </summary>
        public static string Traffic
        {
            get
            {
                return ResourceManager.GetString("Traffic", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to translate.
        /// </summary>
        public static string Translate
        {
            get
            {
                return ResourceManager.GetString("Translate", resourceCulture);
            }
        }
    }
}
